package edu.lms.enums;

public enum NotificationType {
    TUTOR_CANCEL_BOOKING,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REFUND_AVAILABLE,
    REFUND_APPROVED,
    REFUND_REJECTED,
    BOOKING_REMINDER,
    COURSE_APPROVED,
    COURSE_REJECTED,
    COURSE_UPDATED,
    COURSE_DRAFT_APPROVED,
    COURSE_DRAFT_REJECTED
}
